{% set name = "sphinx-data-viewer" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: a7d5e58613562bb745380bfe61ca8b69997998167fd6fa9aea55606c9a4b17e4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - flit-core
    - pip
  run:
    - python >=3.8.0
    - sphinx >=5.0.0

test:
  imports:
    - sphinx_data_viewer
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/useblocks/sphinx-data-viewer
  summary: Sphinx extension to show data in an interactive list view

  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - melund
