{% set name = "sphinx-data-viewer" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 64974f7c2db47609d48a7182881985ec583de3bb520940ea9b3f46357a7afc53

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - poetry >=0.12
    - poetry-core
    - pip
  run:
    - python >=3.6.0
    - sphinx >=4.0.0
    - sphinxcontrib-jquery >=3.0.0

test:
  imports:
    - sphinx_data_viewer
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/useblocks/sphinx-data-viewer
  summary: Sphinx extension to show data in an interactive list view

  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - melund
